stakater/nordmart-apps-gitops-config

01-gabbar/configs/00-build/argocd/stakater-nordmart-review-ui.yaml, 01-gabbar/configs/00-build/argocd/stakater-nordmart-review.yaml, 01-gabbar/configs/00-preview/argocd/stakater-nordmart-review-ui.yaml, 01-gabbar/configs/00-preview/argocd/stakater-nordmart-review.yaml, 01-gabbar/configs/01-dev/argocd/stakater-nordmart-review-ui.yaml, 01-gabbar/configs/01-dev/argocd/stakater-nordmart-review.yaml, 01-gabbar/configs/02-stage/argocd/stakater-nordmart-review-uil.yaml, 01-gabbar/configs/02-stage/argocd/stakater-nordmart-review.yaml, 01-gabbar/configs/03-prod/argocd/stakater-nordmart-review-ui.yaml, 01-gabbar/configs/03-prod/argocd/stakater-nordmart-review.yaml, 02-veeru/configs/00-build/argocd/inventory.yaml, 02-veeru/configs/00-preview/argocd/inventory.yaml, 02-veeru/configs/01-dev/argocd/inventory.yaml, 02-veeru/configs/02-stage/argocd/inventory.yaml, 02-veeru/configs/03-prod/argocd/inventory.yaml, 03-sre/01-dev-test/argocd/00-build/gabbar.yaml, 03-sre/01-dev-test/argocd/00-build/veeru.yaml, 03-sre/01-dev-test/argocd/00-preview/gabbar.yaml, 03-sre/01-dev-test/argocd/00-preview/veeru.yaml, 03-sre/01-dev-test/argocd/01-dev/gabbar.yaml, 03-sre/01-dev-test/argocd/01-dev/veeru.yaml, 03-sre/01-dev-test/argocd/tenant-operator.yaml, 03-sre/02-stage-prod/argocd/02-stage/gabbar.yaml, 03-sre/02-stage-prod/argocd/02-stage/veeru.yaml, 03-sre/02-stage-prod/argocd/03-prod/gabbar.yaml, 03-sre/02-stage-prod/argocd/03-prod/veeru.yaml, 03-sre/02-stage-prod/argocd/tenant-operator.yaml
Reverts stakater/gitops-config-template#62
=> Revert "Update namespace"

01-gabbar/01-stakater-nordmart-review/01-dev/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/01-dev/values.yaml
Reverts stakater/gitops-config-template#108
=> Revert "Update values.yaml"

01-gabbar/01-stakater-nordmart-review/01-dev/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/01-dev/values.yaml
Reverts stakater/gitops-config-template#109
=> Revert "Revert "Update values.yaml""

01-gabbar/01-stakater-nordmart-review/01-dev/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/01-dev/values.yaml
Reverts stakater/gitops-config-template#110
=> Re enable namespace

01-gabbar/01-stakater-nordmart-review/01-dev/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/01-dev/values.yaml
Reverts stakater/gitops-config-template#111
=> Disable namespace

03-sre/01-dev-test/cert-manager/cert-manager-cluster-issuer.yaml
=> Update cluster issuer version

03-sre/01-dev-test/cert-manager/cert-manager-cluster-issuer.yaml
=> Update CA issuer version

03-sre/01-dev-test/argocd/00-build/gabbar.yaml, 03-sre/01-dev-test/argocd/00-build/veeru.yaml, 03-sre/01-dev-test/argocd/00-preview/gabbar.yaml, 03-sre/01-dev-test/argocd/00-preview/veeru.yaml, 03-sre/01-dev-test/argocd/01-dev/gabbar.yaml, 03-sre/01-dev-test/argocd/01-dev/veeru.yaml, 03-sre/01-dev-test/tenant-operator/tenants/gabbar.yaml, 03-sre/01-dev-test/tenant-operator/tenants/veeru.yaml
=> [gabbar+veeru] Support tenant operator app project update tenants

02-veeru/01-stakater-nordmart-inventory/04-demo/values.yaml
Reverts stakater/gitops-config-template#226
=> Revert "testing argocd web hook"

01-gabbar/02-stakater-nordmart-review-ui/00-build/Chart.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Update pipeline chart from v0.0.18 to v0.0.19 & values.yml
=> Update pipeline chart from v0.0.18 to v0.0.19 & values.yml

01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Change stakater-app-sync-and-wait-v1 timeout param
=> Change stakater-app-sync-and-wait-v1 timeout param

01-gabbar/02-stakater-nordmart-review-ui/00-build/Chart.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml, 03-sre/01-dev-test/tekton-config/clustertasks/stakater-app-sync-and-wait-v1.yaml
Add new param to stakater-app-sync-and-wait-v1
=> Change app-sync-and-wait-v1 , Use updated pipeline chart and values

03-sre/01-dev-test/tekton-config/clustertasks/stakater-app-sync-and-wait-v1.yaml
Use argocd app get with refresh to trigger sync for dev/master app 
Related Links :  
https://github.com/argoproj/argo-cd/issues/5592 (Solution Mentioned in this thread )
https://github.com/argoproj/argo-cd/issues/4464
https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-pruning-with-allow-empty-v18
=> Use argocd app get with refresh to trigger sync for dev/master app

01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Increase task stakater-app-sync-and-wait-v1 timeout
=> Increase task stakater-app-sync-and-wait-v1 timeout

01-gabbar/00-argocd-apps/00-build/tekton-pipelines.yaml, 01-gabbar/00-tekton-pipelines/00-build/Chart.yaml, 01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/Chart.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Seprate gabbar and nordmart-review-ui tekton pipelines
=> Seprate gabbar and nordmart-review-ui tekton pipelines

01-gabbar/02-stakater-nordmart-review-ui/00-build/Chart.yaml
Update pipeline chart from 0.0.22 to 0.0.23
=> Update pipeline chart from 0.0.22 to 0.0.23

01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
=> Remove pipelinerun name

README.md
- explain build and preview environment / namespaces
- and improve text for naming convention
=> explain the envs and clarify naming convention

02-veeru/00-argocd-apps/00-build/tekton-pipelines.yaml, 02-veeru/00-tekton-pipelines/00-build/Chart.yaml, 02-veeru/00-tekton-pipelines/00-build/values.yaml
Add tekton pipelines to veeru tenant
=> Add tekton pipelines to veeru tenant

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 02-veeru/00-tekton-pipelines/00-build/values.yaml
Add app-sync-and-wait task to gabbar and veeru pipeline
=> Add app-sync-and-wait task to gabbar and veeru pipeline

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml, 02-veeru/00-tekton-pipelines/00-build/values.yaml
[tenant:pipeline] remove task stakater-validate-app-helm-v1
=> [tenant:pipeline] remove task stakater-validate-app-helm-v1

01-gabbar/03-stakater-nordmart-review-ui-bg-route/01-dev/route.yaml
=> Update route for bg nordmart ui

01-gabbar/03-stakater-nordmart-review-ui-bg-blue/01-dev/values.yaml, 01-gabbar/03-stakater-nordmart-review-ui-bg-green/01-dev/values.yaml
=> Update image tag for bg nordmart ui

01-gabbar/03-stakater-nordmart-review-ui-bg-blue/01-dev/values.yaml, 01-gabbar/03-stakater-nordmart-review-ui-bg-green/01-dev/values.yaml
=> Fix nordmart ui image

01-gabbar/03-stakater-nordmart-review-ui-bg-blue/01-dev/values.yaml, 01-gabbar/03-stakater-nordmart-review-ui-bg-green/01-dev/values.yaml
=> Build and Use linux amd64 images

01-gabbar/03-stakater-nordmart-review-ui-bg-blue/01-dev/values.yaml, 01-gabbar/03-stakater-nordmart-review-ui-bg-green/01-dev/values.yaml, 01-gabbar/03-stakater-nordmart-review-ui-bg-route/01-dev/route.yaml
=> Enable green deployment

01-gabbar/00-argocd-apps/01-dev/stakater-matomo.yaml
=> Add matomo app

01-gabbar/00-argocd-apps/01-dev/stakater-matomo.yaml
=> Change matomo project to default

01-gabbar/00-argocd-apps/01-dev/stakater-allure.yaml
=> Add allure

01-gabbar/00-tekton-pipelines/00-build/Chart.yaml, 01-gabbar/00-tekton-pipelines/00-build/values.yaml
The pipeline chart helm chart has been renamed to 'stakater-tekton-chart". 
Updating the chart dependency for nordmart review pipeline and using the latest version of pipelines. i:e v1.0.0
=> Deploy the latest version of pipeline for nordmart review (SA-1917) (SA-1936)

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/Chart.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Updating the Review UI pipeline to the latest version.
The review ui now use latest version of stakater-tekton-chart
=> Update review ui pipeline

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Changing the Pipeline name for review ui pipeline as tekton does not accept names greater than 63 charater.
Also adidng the missing prnumber parameter.
=> Change pipeline name

01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
The e2e task was missing namespace param. Adding it.
=> Add missing namespace param

00-argocd-apps/02-stage-prod/00-build/gabbar.yaml, 00-argocd-apps/02-stage-prod/00-build/veeru.yaml
We aim to run **tekton pipelines** in **stage** environment so that we have a stable version of pipelines running at all times. **Adding argoCD app to deploy pipelines to stage**.
=> SA-1919 Add argo app for pipelines to stage

01-gabbar/00-tekton-pipelines/00-build/Chart.yaml, 01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/Chart.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Genesis is adding separate machine pools for pipeline workloads. These workloads have a no execute taint on them. 
To schedule pipeline pods on these nodes, we need to add tolerations in pipeline pods.
=> SA-1988 Update tekton chart version and add tolerations

01-gabbar/00-argocd-apps/00-build/stakater-nordmart-reivew.yaml, 01-gabbar/00-argocd-apps/00-build/stakater-nordmart-review-ui.yaml, 02-veeru/00-argocd-apps/00-build/stakater-nordmart-inventory.yaml
**Description**
Argocd Application was removed mistakenly, adding it back
=> [gabbar:build:stakater-nordmart-review-ui] add argocd app

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
as application doesn't come up after 10 mins
=> increase timeout to 15 mins

01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Remove podtemplate from review-ui eventlistener
=> Remove podtemplate from review-ui eventlistener

01-gabbar/02-stakater-nordmart-review-ui/00-build/Chart.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
=> [gabbar:build:stakater-nordmart-review-ui] update tekton chart and create environment cluster task

01-gabbar/00-tekton-pipelines/00-build/Chart.yaml, 01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
=> [gabbar:tektonpipeline] update chart version and pipeline tasks

01-gabbar/00-tekton-pipelines/00-build/values.yaml
[gabbar:tektonpipelines:build] remove create environment task
=> [gabbar:tektonpipelines:build] remove create environment task

01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Disabling e2e test until demo since it needs changes
=> Disabling e2e test until demo

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
=> add qoutes to param

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
update pipeline to use cluster tasks
=> update pipeline to use cluster tasks

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
[ss:tektonpipeline] Fix pipeline values
=> [ss:tektonpipeline] Fix pipeline values

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
=> Fix workspace in values

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
update pipeline for task validation
=> update pipeline for task validation

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
=> Add param pr number to task

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
=> bump tasks version to 1.0.2

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
bump create-environment task version
=> bump create-environment task version

01-gabbar/00-tekton-pipelines/00-build/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/00-build/values.yaml
Update validate environment task to 1.0.4
=> Update validate environment task to 1.0.4

01-gabbar/01-stakater-nordmart-review/01-dev/values.yaml, 01-gabbar/01-stakater-nordmart-review/02-stage/values.yaml, 01-gabbar/01-stakater-nordmart-review/03-prod/values.yaml
=> different secret per environment

01-gabbar/02-stakater-nordmart-review-ui/02-stage/values.yaml, 01-gabbar/02-stakater-nordmart-review-ui/03-prod/values.yaml
=> Fix secret name

01-gabbar/00-tekton-pipelines/00-build/Chart.yaml, 01-gabbar/00-tekton-pipelines/00-build/values.yaml
Updated stakater-tekton-chart to the latest version and added new version of the buildah task.
=> Update buildah task
